# Generated by Django 5.1.5 on 2025-02-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_goods', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('availability', models.BooleanField(null=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(default='no_photo.png', null=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('model_of_instrument', models.CharField(max_length=50, null=True)),
                ('articul', models.CharField(max_length=15, null=True, unique=True)),
                ('category_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_all', to='goods.categorygoods')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='СharacteristicsOfInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, null=True)),
                ('construction', models.CharField(max_length=50, null=True)),
                ('soundboard', models.CharField(max_length=50, null=True)),
                ('guitar_neck', models.CharField(max_length=50, null=True)),
                ('fingerboard', models.IntegerField(null=True)),
                ('guitar_scale', models.CharField(max_length=50, null=True)),
                ('frets', models.IntegerField(null=True)),
                ('pickups', models.CharField(max_length=50, null=True)),
                ('color_accessories', models.CharField(max_length=50, null=True)),
                ('guitar_bridge', models.CharField(max_length=50, null=True)),
                ('pegs', models.CharField(max_length=50, null=True)),
                ('year_release', models.IntegerField(null=True)),
                ('country_release', models.CharField(max_length=50, null=True)),
                ('guitar_pickup_type', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('resistance', models.CharField(max_length=50, null=True)),
                ('built_in_effects', models.CharField(max_length=50, null=True)),
                ('number_of_channels', models.IntegerField(null=True)),
                ('headphone_output', models.CharField(max_length=50, null=True)),
                ('combo_amplifier_type', models.IntegerField(null=True)),
                ('number_of_speakers', models.CharField(max_length=50, null=True)),
                ('effect_loop', models.CharField(max_length=50, null=True)),
                ('expression_pedal', models.CharField(max_length=50, null=True)),
                ('digital_interfaces', models.CharField(max_length=50, null=True)),
                ('effect_type', models.CharField(max_length=50, null=True)),
                ('number_of_strings_in_the_setcombo_amplifier_type', models.IntegerField(null=True)),
                ('tension', models.CharField(max_length=50, null=True)),
                ('core', models.CharField(max_length=50, null=True)),
                ('material', models.CharField(max_length=50, null=True)),
                ('describtion', models.TextField(null=True)),
                ('all_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='describe', to='goods.allgoods')),
            ],
        ),
        migrations.AddIndex(
            model_name='allgoods',
            index=models.Index(fields=['-price'], name='goods_allgo_price_8e9ed0_idx'),
        ),
    ]
